#pragma once
#include <stdint.h>

typedef int32_t app_err_t;

#define APP_OK 0

#define APP_ERR_BASE 0x1000
#define APP_ERR_GENERIC (APP_ERR_BASE + 0)
#define APP_ERR_UNKNOWN_COMMAND (APP_ERR_BASE + 1)
#define APP_ERR_SPI1_ERROR (APP_ERR_BASE + 3)
#define APP_ERR_SPI2_ERROR (APP_ERR_BASE + 4)
#define APP_ERR_ACCEL_INIT_FAILED (APP_ERR_BASE + 5)
#define APP_ERR_LOGGER_INIT_FAILED (APP_ERR_BASE + 6)
#define APP_ERR_IO_INIT_FAILED (APP_ERR_BASE + 6)
#define APP_ERR_MEMORY_ALLOCATION_FAILED (APP_ERR_BASE + 6)
#define APP_ERR_NOT_SUPPORTED (APP_ERR_BASE + 7)
#define APP_ERR_SD_MOUNT_FAILED (APP_ERR_BASE + 8)
#define APP_ERR_INVALID_STATE (APP_ERR_BASE + 9)
#define APP_ERR_INVALID_ARG (APP_ERR_BASE + 10)
#define APP_ERR_MEMORY_ALLOCATION (APP_ERR_BASE + 11)
#define APP_ERR_TASK_CREATION (APP_ERR_BASE + 12)
#define APP_ERR_STM32_CONFIG_TIMEOUT (APP_ERR_BASE + 13)
