#pragma once

#include <stdint.h>
#include <stddef.h>

// Auto-generated by update-embed-files.py

typedef struct {
    const char* path;
    const uint8_t* start;
    const uint8_t* end;
    const char* mime_type;
    int is_gzipped;
} embedded_asset_t;

const embedded_asset_t* embedded_asset_find(const char* path);
