#pragma once

#include "hal/ws2812.h"
#include "sdkconfig.h"

#define ESP32

// Application is always in LOGGER mode (receives raw frames from STM32 via SPI)
// Previously supported roles (SINGLE, ACCEL_READER) have been removed.

#define SINGLE_APP
// #define LOGGER_APP
// #define ACCEL_READER_APP
#define USE_S3_MINI_BOARD


#define USE_FEATURE_BUTTON
// #define USE_PIEZO_COMPARATOR

// SPI Host Configuration
// Mapped per-target to available general-purpose SPI controllers.
#if defined(CONFIG_IDF_TARGET_ESP32S3)
// ESP32-S3 has SPI2_HOST and SPI3_HOST as general-purpose
#define ACCEL_SPI_HOST SPI3_HOST   // General-purpose SPI - safe to use with PSRAM
#define SDCARD_SPI_HOST SPI2_HOST  // General-purpose SPI - safe to use with PSRAM

#if defined(USE_S3_MINI_BOARD)
#define LINK_SPI_HOST SPI3_HOST  // Shares SPI3_HOST with accelerometer (same pins)
#else
#define LINK_SPI_HOST SPI2_HOST  // Not used on ESP32-S3, but defined for compatibility
#endif
#elif defined(CONFIG_IDF_TARGET_ESP32S2) || defined(CONFIG_IDF_TARGET_ESP32)
// Use SPI3_HOST for accelerometer, SPI2_HOST for SD card
#define ACCEL_SPI_HOST SPI2_HOST
#define SDCARD_SPI_HOST SPI2_HOST
#define LINK_SPI_HOST SPI3_HOST  // Not used on ESP32/ESP32-S2, but defined for compatibility
#else
#error "Unsupported ESP32 target for SPI host configuration"
#endif
#define DAC_VREF_MV 3300

#define DEBUG_LOGGER_WRITES 1
#define DIAGNOSTIC_IN_LOG
#define DIAGNOSTIC_IN_LOG_PERIOD_SEC 30U

// Accelerometer SPI clock (Hz). LSM6DS3 supports up to 10 MHz, but lower speeds
// are more reliable. Reduced to 1 MHz for debugging WHO_AM_I issues.
#ifndef ACCEL_SPI_FREQ_HZ
#define ACCEL_SPI_FREQ_HZ (3U * 1000U * 1000U)
#endif

// Accelerometer self-test configuration
// Set to 1 to enable self-test during initialization, 0 to disable
#ifndef ENABLE_ACCEL_SELF_TEST
#define ENABLE_ACCEL_SELF_TEST 1
#endif

// Enable optional gyro logging (duplicates accelerometer data into gyro fields).
#define LOG_GYRO 1
#define LED_COLOR_ORDER 0

// ACC_INT_ACTIVE_HIGH: Set to 1 for active-high interrupts (recommended for high ODR)
// At high ODR (6.66 kHz), active-low stays low most of the time, missing edge triggers
#ifndef ACC_INT_ACTIVE_HIGH
#define ACC_INT_ACTIVE_HIGH 1
#endif

// Accelerometer emulation configuration for high-frequency testing.
// Define USET_EMULATION to enable software-timed emulation of accelerometer interrupts.
// When enabled, the LIS3DH is configured normally and read over SPI,
// but notifications are generated by a software timer at EMU_FREQ.
#ifndef EMU_FREQ
#define EMU_FREQ 6500U
#endif


// SD card tuning (SPI via SDSPI host).
// These macros define the SPI clock for the SD card and basic FAT mount options.
// Increase SDCARD_SPI_FREQ_KHZ cautiously to explore the maximum sustainable rate.

#ifndef SDCARD_SPI_FREQ_KHZ
#ifdef CONFIG_IDF_TARGET_ESP32S3
#define SDCARD_SPI_FREQ_KHZ 20000U
#else
#define SDCARD_SPI_FREQ_KHZ 20000U  // 35 MHz - default for other ESP32 variants
#endif
#endif

#ifndef SDCARD_MAX_FILES
#define SDCARD_MAX_FILES 1
#endif

#ifndef SDCARD_ALLOC_UNIT
#define SDCARD_ALLOC_UNIT (16 * 1024)
#endif

#if defined(CONFIG_IDF_TARGET_ESP32S3) && defined(USE_S3_MINI_BOARD)
// ESP32-S3 Mini Configuration
// Pin assignments using only GPIO pins 1-13 (GPIO 3 avoided - strapping pin)
// Configuration: 2 independent SPI buses, 1 interrupt, LED, external button, no UART
// These pins are safe because they are:
// - Not involved in bootstrapping (GPIO 3 is strapping pin - AVOIDED)
// - Not linked to flash memory or PSRAM (won't interfere with storage/memory)
// - Not dedicated to USB or JTAG (free for general use)
// - No special hardware connections (freely assignable)
// Note: GPIO 1 can conflict with UART0 TX, but UART functionality is not used

#define USE_USB_FILE_SERVER  // Use USB file server to download files from SD card (TinyUSB supported)
#define USE_RGB_LED
#define USE_LED_OUT

#define BUTTON_ENTER_GPIO 0
#define BUTTON_EXTERNAL_GPIO 12

#define ACC_INT_GPIO 10
#define ACC_SPI_CLK_GPIO 1
#define ACC_SPI_MISO_GPIO 2
#define ACC_SPI_MOSI_GPIO 4
#define ACC_SPI_CS_GPIO 5

#define LED_OUT_GPIO 11
#define RGB_LED_GPIO 48

#define STM_RESET_GPIO 3

#define LINK_INT_GPIO 10
#define LINK_SPI_CLK_GPIO 1
#define LINK_SPI_MISO_GPIO 2
#define LINK_SPI_MOSI_GPIO 4
#define LINK_SPI_CS_GPIO 5

// SD Card SPI Configuration (SPI2_HOST) - Second SPI bus (independent pins)
// Uses different pins from ACCEL/LINK SPI to avoid conflicts
#define SD_MOUNT_PATH "/sdcard"
#define SD_SPI_CLK_GPIO 6
#define SD_SPI_MISO_GPIO 7
#define SD_SPI_MOSI_GPIO 8
#define SD_SPI_CS_GPIO 9

#define DAC_OUT_1_GPIO -1
#define DAC_OUT_2_GPIO -1

#elif defined(CONFIG_IDF_TARGET_ESP32)
// ESP32 Configuration
#define USE_WIFI
#define USE_WEB_FILE_SEREVER
// #define USE_USB_FILE_SERVER  // Use USB file server to download files from SD card

#define BUTTON_ENTER_GPIO 0      // WARNING: This is a strapping pin; if held LOW on boot, the device enters bootloader mode.
#define BUTTON_EXTERNAL_GPIO 36  // MOVED to a safe, input-only pin.

#define ACC_INT_GPIO 22       // 21  // Changed from 25 (not working) to 21 (safe, commonly used for interrupts)
#define ACC_SPI_CLK_GPIO 5    // 26
#define ACC_SPI_MISO_GPIO 18  // 27  // SAO
#define ACC_SPI_MOSI_GPIO 19  // 32  // SDA
#define ACC_SPI_CS_GPIO 23    // 25

#define SD_MOUNT_PATH "/sdcard"

#define LED_OUT_GPIO 4  // OK.

#define LINK_INT_GPIO 21       // 22  // 10 on s3
#define LINK_SPI_CLK_GPIO 26   // 5    // 1 on s3
#define LINK_SPI_MISO_GPIO 27  // 18  // 2 on s3
#define LINK_SPI_MOSI_GPIO 32  // 19  // 4 on s3
#define LINK_SPI_CS_GPIO 25    // 23    // 5 on s3

#else
#error "Unsupported ESP32 target. Please define CONFIG_IDF_TARGET_ESP32S2, CONFIG_IDF_TARGET_ESP32S3, CONFIG_IDF_TARGET_ESP32, or CONFIG_IDF_TARGET_ESP32C3"
#endif

// Task Priority Definitions
#define TASK_PRIORITY_LED_BLINK 1
#define TASK_PRIORITY_USB_BOOT_CMD 1
#define TASK_PRIORITY_APP_LOGIC 2
#define TASK_PRIORITY_IO_MANAGER 3
#define TASK_PRIORITY_LOGGER 6
#define TASK_PRIORITY_ACCEL_TASK 8
#define TASK_PRIORITY_PZ_TASK 10
#if defined(USE_WIFI)
#define TASK_PRIORITY_WIFI_EVENT 4
#endif
#if defined(USE_WEB_FILE_SEREVER)
#define TASK_PRIORITY_WEB_SERVER 5
#endif

// Task core affinity configuration (0 or 1 on dual-core ESP32)
// Use tskNO_AFFINITY if you want the scheduler to choose.

#define CORE_APP_LOGIC 0
#define CORE_IO_MANAGER 1
#define CORE_ACCEL_TASK 0
#define CORE_LOGGER_PROC 1
#define CORE_LOGGER_WRITE 1

// Task Stack Size Definitions (all values expressed in bytes for ESP-IDF)
// Optimized LED task stack - reduced from 3072 to 1536 bytes
// LED task only does simple GPIO operations and delays - no complex operations needed
// Stack usage reduced by removing expensive printf-style logging calls
#define TASK_STACK_SIZE_LED_BLINK (3072U)
#define TASK_STACK_SIZE_USB_BOOT_CMD (1024U)
#define TASK_STACK_SIZE_APP_LOGIC (4096U)
#define TASK_STACK_SIZE_IO_MANAGER (3048U)
#define TASK_STACK_SIZE_LOGGER (4096U)
#define TASK_STACK_SIZE_ACCEL_TASK (6000U)
#define TASK_STACK_SIZE_PZ_TASK (2048U)

#if defined(USE_WIFI)
#define TASK_STACK_SIZE_WIFI_EVENT (4096U)

// WiFi Credentials
#define WIFI_STA_SSID "902studio"
#define WIFI_STA_PASSWORD "Emc902NetWifiNew"
#define WIFI_AP_SSID "3PLogger"
#define WIFI_AP_PASSWORD "3PLogger"
#define WIFI_AP_CHANNEL 0

// WiFi Mode Configuration
// Enable one of the following WiFi modes:
// #define WIFI_MODE_STA_ONLY  // Station mode only
#define WIFI_MODE_AP_ONLY  // Access Point mode only
                           // #define WIFI_MODE_STA_AP  // Both Station and Access Point modes
#endif
#if defined(USE_WEB_FILE_SEREVER)
#define TASK_STACK_SIZE_WEB_SERVER (8192U)
#endif
